# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\"\x1f\n\x0e\x41\x64\x64TaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\"\n\x0f\x41\x64\x64TaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x11\n\x0fGetTasksRequest\"(\n\x10GetTasksResponse\x12\x14\n\x05tasks\x18\x01 \x03(\x0b\x32\x05.Task\"!\n\x13\x43ompleteTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\'\n\x14\x43ompleteTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"4\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\x32\xa9\x01\n\x0bTodoService\x12,\n\x07\x41\x64\x64Task\x12\x0f.AddTaskRequest\x1a\x10.AddTaskResponse\x12/\n\x08GetTasks\x12\x10.GetTasksRequest\x1a\x11.GetTasksResponse\x12;\n\x0c\x43ompleteTask\x12\x14.CompleteTaskRequest\x1a\x15.CompleteTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDTASKREQUEST']._serialized_start=14
  _globals['_ADDTASKREQUEST']._serialized_end=45
  _globals['_ADDTASKRESPONSE']._serialized_start=47
  _globals['_ADDTASKRESPONSE']._serialized_end=81
  _globals['_GETTASKSREQUEST']._serialized_start=83
  _globals['_GETTASKSREQUEST']._serialized_end=100
  _globals['_GETTASKSRESPONSE']._serialized_start=102
  _globals['_GETTASKSRESPONSE']._serialized_end=142
  _globals['_COMPLETETASKREQUEST']._serialized_start=144
  _globals['_COMPLETETASKREQUEST']._serialized_end=177
  _globals['_COMPLETETASKRESPONSE']._serialized_start=179
  _globals['_COMPLETETASKRESPONSE']._serialized_end=218
  _globals['_TASK']._serialized_start=220
  _globals['_TASK']._serialized_end=272
  _globals['_TODOSERVICE']._serialized_start=275
  _globals['_TODOSERVICE']._serialized_end=444
# @@protoc_insertion_point(module_scope)
